# Generated by Django 3.0.7 on 2020-06-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200623_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('indoor', 'Indoor'), ('out door', 'Out door')], max_length=200, null=True),
        ),
    ]
